CREATE TABLE events
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                     VARCHAR(255)                            NOT NULL,
    description              TEXT,
    event_type               VARCHAR(100)                            NOT NULL,
    venue_name               VARCHAR(255),
    venue_address            TEXT,
    event_date               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    total_tickets            INTEGER                                 NOT NULL,
    available_tickets        INTEGER                                 NOT NULL,
    max_tickets_per_purchase INTEGER                                 NOT NULL,
    ticket_price             DOUBLE PRECISION                        NOT NULL,
    status                   VARCHAR(50)                             NOT NULL,
    created_by               BIGINT                                  NOT NULL,
    created_at               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at               TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    event_id       BIGINT                                  NOT NULL,
    ticket_count   INTEGER                                 NOT NULL,
    total_amount   DOUBLE PRECISION                        NOT NULL,
    status         VARCHAR(50)                             NOT NULL,
    order_method   VARCHAR(50)                             NOT NULL,
    transaction_id VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE tickets
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id    BIGINT                                  NOT NULL,
    event_id    BIGINT                                  NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    ticket_code VARCHAR(255)                            NOT NULL,
    seat_number VARCHAR(50),
    status      VARCHAR(50)                             NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tickets PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username           VARCHAR(50)                             NOT NULL,
    email              VARCHAR(100)                            NOT NULL,
    password_encrypted VARCHAR(255)                            NOT NULL,
    first_name         VARCHAR(100),
    last_name          VARCHAR(100),
    role               VARCHAR(20)                             NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE tickets
    ADD CONSTRAINT uc_tickets_ticket_code UNIQUE (ticket_code);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);